version: '3.8'

services:
  llm-api:
    build: .
    container_name: llm-api
    ports:
      - "8090:8090"
    volumes:
      - ./:/app
    networks:
      - shared-net
    tty: true

networks:
  shared-net:
    external: true
    name: deep-audio-network